// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-VbEQjGERROyKHgupcrPo9Nujt7DZBIw',
    appId: '1:952918330555:web:0bb18f33143a52f313ed9e',
    messagingSenderId: '952918330555',
    projectId: 'watchtower-dev-8c0f7',
    authDomain: 'watchtower-dev-8c0f7.firebaseapp.com',
    storageBucket: 'watchtower-dev-8c0f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi8eqhR1VmFw3DnFEVXpYPGVZfWvhY6zg',
    appId: '1:952918330555:android:0fd3ed52df7f496913ed9e',
    messagingSenderId: '952918330555',
    projectId: 'watchtower-dev-8c0f7',
    storageBucket: 'watchtower-dev-8c0f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxvPm1-1PHc_hcre4Xt8dRa7vBI9Viak',
    appId: '1:952918330555:ios:9b678a8757bafb0e13ed9e',
    messagingSenderId: '952918330555',
    projectId: 'watchtower-dev-8c0f7',
    storageBucket: 'watchtower-dev-8c0f7.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxvPm1-1PHc_hcre4Xt8dRa7vBI9Viak',
    appId: '1:952918330555:ios:9b678a8757bafb0e13ed9e',
    messagingSenderId: '952918330555',
    projectId: 'watchtower-dev-8c0f7',
    storageBucket: 'watchtower-dev-8c0f7.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-VbEQjGERROyKHgupcrPo9Nujt7DZBIw',
    appId: '1:952918330555:web:9aee596104226b4c13ed9e',
    messagingSenderId: '952918330555',
    projectId: 'watchtower-dev-8c0f7',
    authDomain: 'watchtower-dev-8c0f7.firebaseapp.com',
    storageBucket: 'watchtower-dev-8c0f7.firebasestorage.app',
  );
}
